# Generated by Django 5.0.3 on 2024-03-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intra_id', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_status', models.BooleanField(default=False)),
                ('win', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
            ],
        ),
    ]
