services:
  frontend:
    container_name: frontend
    image: frontend
    pull_policy: never
    build: ./frontend
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
    volumes:
      - type: bind
        source: ./frontend/dist
        target: /var/www

  db:
    container_name: db
    image: postgres:13
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
  backend:
    container_name: backend
    image: backend
    build: ./backend
    pull_policy: never
    expose:
      - "8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
